# Generated by Django 6.0.2 on 2026-02-06 23:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in chore lists.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional details to help complete the chore.')),
                ('points', models.PositiveIntegerField(default=0, help_text='Points awarded when the chore is completed.', validators=[django.core.validators.MinValueValidator(0)])),
                ('penalize_incomplete', models.BooleanField(default=False, help_text='Deduct points if the chore is not completed by the due date.')),
                ('penalty_amount', models.IntegerField(default=0, help_text='Percent of points to deduct for incomplete chores (0-100).', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_recurring', models.BooleanField(default=True)),
                ('recurrence_day_of_week', models.CharField(blank=True, help_text='Weekly schedule label (e.g., "Monday").', max_length=60, null=True)),
                ('recurrence_day_of_month', models.CharField(blank=True, help_text='Monthly schedule label (e.g., "15").', max_length=90, null=True)),
                ('recurrence', models.CharField(blank=True, choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], default=None, help_text='Recurrence cadence when the chore is recurring.', max_length=1, null=True)),
                ('instructions_video', models.FileField(blank=True, help_text='Optional video stored in the system.', null=True, upload_to='chore/instruction/videos/')),
                ('instructions_video_name', models.CharField(blank=True, help_text='Filename to show in the UI for the instructions video.', max_length=255)),
                ('instructions_video_source', models.URLField(blank=True, help_text='External video link if not stored locally.', null=True)),
                ('notes', models.JSONField(blank=True, help_text='Optional structured metadata for the chore.', null=True)),
                ('time_due', models.TimeField(blank=True, help_text='Optional time of day when the chore is due.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in equipment lists.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional details about the equipment.')),
                ('notes', models.JSONField(blank=True, help_text='Optional structured metadata for the equipment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in location lists.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional details about the location.')),
                ('notes', models.JSONField(blank=True, help_text='Optional structured metadata for the location.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(help_text='Date and time when the assignment is due.')),
                ('pending_approval', models.BooleanField(default=False, help_text='Awaiting approval before points are awarded.')),
                ('approved', models.BooleanField(default=False, help_text='Approved and points have been awarded.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, help_text='Optional structured metadata for the assignment.', null=True)),
                ('closed', models.BooleanField(default=False, help_text='Closed assignments cannot be completed or approved.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='User responsible for completing the chore.', on_delete=django.db.models.deletion.CASCADE, related_name='chore_assignments', to=settings.AUTH_USER_MODEL)),
                ('chore', models.ForeignKey(help_text='Chore being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='chores.chore')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo evidence.', null=True, upload_to='chore/evidence/photos/')),
                ('video', models.FileField(blank=True, help_text='Optional video evidence.', null=True, upload_to='chore/evidence/videos/')),
                ('notes', models.JSONField(blank=True, help_text='Optional structured metadata for the evidence.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(help_text='Assignment this evidence belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='chores.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='equipment',
            field=models.ManyToManyField(blank=True, help_text='Equipment required for this chore.', related_name='chores', to='chores.equipment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where the equipment is stored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='chores.location'),
        ),
        migrations.AddField(
            model_name='chore',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Where the chore is usually done.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='chores.location'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in task lists.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional details to help complete the task.')),
                ('steps', models.JSONField(blank=True, help_text='Optional structured steps and media links.', null=True)),
                ('notes', models.JSONField(blank=True, help_text='Optional structured metadata for the task.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, help_text='Equipment required for this task.', related_name='tasks', to='chores.equipment')),
            ],
        ),
        migrations.AddField(
            model_name='chore',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='Optional steps that make up this chore.', related_name='chores', to='chores.task'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('is_recurring', True), ('recurrence__isnull', True), _negated=True), name='chore_recurrence_consistency'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', 'W'), ('recurrence_day_of_week__isnull', True), _negated=True), name='chore_weekly_requires_day_of_week'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', 'W'), ('recurrence_day_of_week', ''), _negated=True), name='chore_weekly_day_of_week_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', 'W'), ('recurrence_day_of_month__isnull', False), _negated=True), name='chore_weekly_day_of_month_must_be_null'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', 'M'), ('recurrence_day_of_month__isnull', True), _negated=True), name='chore_monthly_requires_day_of_month'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', 'M'), ('recurrence_day_of_month', ''), _negated=True), name='chore_monthly_day_of_month_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('recurrence', 'M'), ('recurrence_day_of_week__isnull', False), _negated=True), name='chore_monthly_day_of_week_must_be_null'),
        ),
    ]
