# Generated by Django 6.0.2 on 2026-02-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial_chore_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(help_text='Short label shown in equipment lists.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Short label shown in location lists.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Short label shown in task lists.', max_length=255, unique=True),
        ),
    ]
