# Generated by Django 6.0.2 on 2026-02-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_make_equipment_location_task_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo of the equipment.', null=True, upload_to='chore/equipment/images/'),
        ),
    ]
