# Generated by Django 6.0.2 on 2026-02-07 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_add_equipment_photo_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='age_restricted',
            field=models.BooleanField(default=False, help_text='Whether this chore should be restricted based on user age.'),
        ),
        migrations.AddField(
            model_name='chore',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age required to be assigned this chore (if age_restricted is True).', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('age_restricted', False), ('minimum_age__isnull', False), _negated=True), name='chore_minimum_age_requires_age_restricted'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('age_restricted', True), ('minimum_age__isnull', True), _negated=True), name='chore_age_restricted_requires_minimum_age'),
        ),
    ]
