# Generated by Django 6.0.2 on 2026-02-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_add_age_restrictions_to_chores'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assign_to_all',
            field=models.BooleanField(default=False, help_text='Whether this chore should be automatically assigned to all children when chores are assigned.'),
        ),
    ]
