# Generated by Django 6.0.2 on 2026-02-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_add_assign_to_all_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Whether this chore is currently disabled and should not be assigned.'),
        ),
    ]
