# Generated by Django 6.0.2 on 2026-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Optional birth date of the user.', null=True),
        ),
    ]
